apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sandboxed-containers-operator
  namespace: {{ .Values.namespace }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: sandboxed-containers-operator
  source: {{ if .Values.dev.enabled }}osc-operator-dev-catalog{{ else }}redhat-operators{{ end }}
  sourceNamespace: openshift-marketplace
  startingCSV: sandboxed-containers-operator.v{{ .Chart.AppVersion }}
