apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trustee-operator
  namespace: {{ .Values.namespace }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: trustee-operator
  source: {{ if .Values.dev.enabled }}trustee-operator-dev-catalog{{ else }}redhat-operators{{ end }}
  sourceNamespace: openshift-marketplace
