confidential:
  enabled: true

nodeSelector:
  labels:
    baremetal:
        node-role.kubernetes.io/kata-pool: ""
    cloud:
        node-role.kubernetes.io/kata-remote-pool: ""

# Cloud Mode
peerpods:
  enabled: true
  provider: "azure"
  providersConfigs:
    all:
      VXLAN_PORT: "9000"
      PROXY_TIMEOUT: "5m"
      PODVM_IMAGE_URI: "oci::gcr.io/osc-gcp/podvm-disk-oci:rhel95_dmverity_luks"
      # Set if confidential is enabled
      INITDATA: ""

    gcp:
      PODVM_IMAGE_NAME: ""
      GCP_PROJECT_ID: "it-cloud-gcp-prod-osc-devel"
      GCP_ZONE: "us-central1-a"
      GCP_NETWORK: "default"
      GCP_MACHINE_TYPE: "n1-standard-1"
    
    azure:
      AZURE_IMAGE_ID: ""
      AZURE_RESOURCE_GROUP: ""
      AZURE_REGION: ""
      AZURE_SUBNET_ID: ""
      AZURE_NSG_ID: ""
      AZURE_INSTANCE_SIZE: ""
